[package]
name = "quicksilver-roguelike"
version = "0.1.0"
authors = ["lonnen <chris.lonnen@gmail.com>"]
edition = "2018"

[dependencies]
quicksilver = { version = "0.3.15", default-features = false, features = ["fonts", "saving"]}